theme: jekyll-theme-minimal
title: VA Slack Enterprise Handbook
description: Put something descriptive here!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
